# Generated by Django 5.2.7 on 2025-10-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.AddField(
            model_name='book',
            name='janr',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
