# Generated by Django 5.2.7 on 2025-10-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportedFile',
        ),
        migrations.RemoveField(
            model_name='book',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication_year',
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
